/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TravelOrdersImport } from './routes/travelOrders'
import { Route as TravelOrdersNewImport } from './routes/travelOrders.new'
import { Route as TravelOrdersIdImport } from './routes/travelOrders.$id'
import { Route as TravelOrdersIdEditImport } from './routes/travelOrders.$id_.edit'

// Create/Update Routes

const TravelOrdersRoute = TravelOrdersImport.update({
  path: '/travelOrders',
  getParentRoute: () => rootRoute,
} as any)

const TravelOrdersNewRoute = TravelOrdersNewImport.update({
  path: '/new',
  getParentRoute: () => TravelOrdersRoute,
} as any)

const TravelOrdersIdRoute = TravelOrdersIdImport.update({
  path: '/$id',
  getParentRoute: () => TravelOrdersRoute,
} as any)

const TravelOrdersIdEditRoute = TravelOrdersIdEditImport.update({
  path: '/$id/edit',
  getParentRoute: () => TravelOrdersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travelOrders': {
      id: '/travelOrders'
      path: '/travelOrders'
      fullPath: '/travelOrders'
      preLoaderRoute: typeof TravelOrdersImport
      parentRoute: typeof rootRoute
    }
    '/travelOrders/$id': {
      id: '/travelOrders/$id'
      path: '/$id'
      fullPath: '/travelOrders/$id'
      preLoaderRoute: typeof TravelOrdersIdImport
      parentRoute: typeof TravelOrdersImport
    }
    '/travelOrders/new': {
      id: '/travelOrders/new'
      path: '/new'
      fullPath: '/travelOrders/new'
      preLoaderRoute: typeof TravelOrdersNewImport
      parentRoute: typeof TravelOrdersImport
    }
    '/travelOrders/$id/edit': {
      id: '/travelOrders/$id/edit'
      path: '/$id/edit'
      fullPath: '/travelOrders/$id/edit'
      preLoaderRoute: typeof TravelOrdersIdEditImport
      parentRoute: typeof TravelOrdersImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  TravelOrdersRoute: TravelOrdersRoute.addChildren({
    TravelOrdersIdRoute,
    TravelOrdersNewRoute,
    TravelOrdersIdEditRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/travelOrders"
      ]
    },
    "/travelOrders": {
      "filePath": "travelOrders.tsx",
      "children": [
        "/travelOrders/$id",
        "/travelOrders/new",
        "/travelOrders/$id/edit"
      ]
    },
    "/travelOrders/$id": {
      "filePath": "travelOrders.$id.tsx",
      "parent": "/travelOrders"
    },
    "/travelOrders/new": {
      "filePath": "travelOrders.new.tsx",
      "parent": "/travelOrders"
    },
    "/travelOrders/$id/edit": {
      "filePath": "travelOrders.$id_.edit.tsx",
      "parent": "/travelOrders"
    }
  }
}
ROUTE_MANIFEST_END */
